import { useEffect, useMemo } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Link } from "react-router-dom";
import { fetchAttributes, fetchCategories, fetchProducts, selectAllAttributes, selectAllCategories, selectAllProducts } from "../../store/catalogueSlice";

const AdminDashboardPage = () => {
  const dispatch = useDispatch();
  const products = useSelector(selectAllProducts);
  const categories = useSelector(selectAllCategories);
  const attributes = useSelector(selectAllAttributes);
  useEffect(() => { dispatch(fetchProducts({ pagination: { page: 1, pageSize: 5000 } })); dispatch(fetchCategories()); dispatch(fetchAttributes()); }, [dispatch]);
  const variantCount = useMemo(() => products.reduce((sum, product) => sum + Number(product.variant_count || 1), 0), [products]);

  return <div className="grid gap-6"><section className="overflow-hidden rounded-[2rem] bg-gradient-to-br from-slate-950 via-blue-700 to-sky-400 p-6 text-white shadow-soft sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-3xl"><p className="m-0 text-xs font-bold uppercase tracking-[0.28em] text-white/80">Admin overview</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Run your catalogue from one control center</h2><p className="mt-4 text-sm leading-7 text-white/85 sm:text-base">Manage products grouped by product ID, edit row-level variants, and import supplier files with smart column mapping.</p></div><div className="flex flex-wrap gap-3"><Link to="/admin/products/new" className="btn-outline border-white/20 bg-white text-slate-950 hover:bg-slate-100">Create product</Link><Link to="/admin/import" className="btn-outline border-white/20 bg-white/10 text-white hover:bg-white/15 hover:text-white">Open importer</Link></div></div></section><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="stat-card"><strong className="text-3xl font-bold text-slate-900">{products.length}</strong><div className="mt-2 text-sm text-slate-500">Grouped products</div></div><div className="stat-card"><strong className="text-3xl font-bold text-slate-900">{variantCount}</strong><div className="mt-2 text-sm text-slate-500">Variant rows</div></div><div className="stat-card"><strong className="text-3xl font-bold text-slate-900">{categories.length}</strong><div className="mt-2 text-sm text-slate-500">Categories</div></div><div className="stat-card"><strong className="text-3xl font-bold text-slate-900">{attributes.length}</strong><div className="mt-2 text-sm text-slate-500">Attributes</div></div></div><div className="grid gap-4 xl:grid-cols-[1.35fr_1fr]"><div className="surface-card p-6"><h3 className="mt-0 text-xl font-semibold text-slate-900">Operational highlights</h3><ul className="m-0 list-disc space-y-3 pl-5 text-sm leading-7 text-slate-600"><li>Repeated <code>product_id</code> values are grouped into one product with many variants.</li><li>The importer can map vendor columns like <code>Product Name</code> and <code>Stock Qty</code>.</li><li>Dynamic fields such as <code>battery</code>, <code>material</code>, and <code>capacity</code> are preserved.</li></ul></div><div className="surface-card p-6"><h3 className="mt-0 text-xl font-semibold text-slate-900">Quick actions</h3><div className="grid gap-3"><Link to="/admin/products" className="btn-outline justify-start">Browse products</Link><Link to="/admin/products/new" className="btn-outline justify-start">Add a product</Link><Link to="/admin/import" className="btn-outline justify-start">Import vendor CSV</Link></div></div></div></div>;
};

export default AdminDashboardPage;