import { useEffect, useMemo, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Link } from "react-router-dom";
import LoadingPanel from "../../components/LoadingPanel";
import { fetchCategories, fetchProducts, selectAllCategories, selectAllProducts, selectLoadingByAction } from "../../store/catalogueSlice";

const AdminCategoriesPage = () => {
  const dispatch = useDispatch(); const categories = useSelector(selectAllCategories); const products = useSelector(selectAllProducts); const loading = useSelector(selectLoadingByAction("fetchCategories")); const loadingProducts = useSelector(selectLoadingByAction("fetchProducts")); const [search, setSearch] = useState("");
  useEffect(() => { dispatch(fetchCategories()); dispatch(fetchProducts({ pagination: { page: 1, pageSize: 5000 } })); }, [dispatch]);
  const summaries = useMemo(() => categories.map((category) => { const categoryProducts = products.filter((product) => String(product.category_id) === String(category.category_id) || String(product.category_name) === String(category.name)); const variantCount = categoryProducts.reduce((sum, product) => sum + Number(product.variant_count || 1), 0); const brands = Array.from(new Set(categoryProducts.map((product) => product.brand).filter(Boolean))); return { ...category, productCount: categoryProducts.length, variantCount, brandCount: brands.length }; }).filter((category) => !search || category.name.toLowerCase().includes(search.toLowerCase())), [categories, products, search]);
  const totalVariants = useMemo(() => summaries.reduce((sum, category) => sum + category.variantCount, 0), [summaries]);
  if ((loading || loadingProducts) && !categories.length && !products.length) return <LoadingPanel title="Loading categories" message="Collecting category summaries, grouped products, and variant totals." variant="cards" />;
  return <div className="grid gap-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="m-0 text-3xl font-bold text-slate-900">Categories</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-slate-500">Monitor how grouped products are distributed across categories and identify where most variants live.</p></div><Link to="/admin/products" className="btn-outline">Open products</Link></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><div className="stat-card"><strong className="text-3xl font-bold text-slate-900">{categories.length}</strong><div className="mt-2 text-sm text-slate-500">Categories</div></div><div className="stat-card"><strong className="text-3xl font-bold text-slate-900">{products.length}</strong><div className="mt-2 text-sm text-slate-500">Grouped products</div></div><div className="stat-card"><strong className="text-3xl font-bold text-slate-900">{totalVariants}</strong><div className="mt-2 text-sm text-slate-500">Variant rows</div></div></div><div className="surface-card grid gap-4 p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="m-0 text-xl font-semibold text-slate-900">Category insights</h2><p className="mt-2 text-sm text-slate-500">Search categories and inspect how many products, variants, and brands each one contains.</p></div><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search categories" className="field-input max-w-sm" /></div>{!summaries.length ? <div className="text-sm text-slate-500">No categories matched your search.</div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{summaries.map((category) => <article key={category.category_id || category.slug} className="rounded-3xl border border-slate-200 bg-slate-50/70 p-5"><div className="grid gap-3"><div><h3 className="m-0 text-lg font-semibold text-slate-900">{category.name}</h3><p className="mt-2 text-sm text-slate-500">Slug: {category.slug || "—"}</p></div><div className="grid gap-2 text-sm text-slate-600"><div><strong>Products:</strong> {category.productCount}</div><div><strong>Variants:</strong> {category.variantCount}</div><div><strong>Brands:</strong> {category.brandCount}</div></div></div></article>)}</div>}</div></div>;
};

export default AdminCategoriesPage;