import { useEffect, useMemo, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Link } from "react-router-dom";
import LoadingPanel from "../../components/LoadingPanel";
import { fetchAttributes, fetchProducts, selectAllAttributes, selectAllProducts, selectLoadingByAction } from "../../store/catalogueSlice";

const DEFAULT_VARIANT_FIELDS = new Set(["color", "storage", "screen_size"]);

const AdminAttributesPage = () => {
  const dispatch = useDispatch(); const attributes = useSelector(selectAllAttributes); const products = useSelector(selectAllProducts); const loading = useSelector(selectLoadingByAction("fetchAttributes")); const loadingProducts = useSelector(selectLoadingByAction("fetchProducts")); const [search, setSearch] = useState(""); const [scope, setScope] = useState("all");
  useEffect(() => { dispatch(fetchAttributes()); dispatch(fetchProducts({ pagination: { page: 1, pageSize: 5000 } })); }, [dispatch]);
  const summaries = useMemo(() => attributes.map((attribute) => { const productsUsing = products.filter((product) => (product.option_names || []).includes(attribute.attribute_id)); const valueCount = productsUsing.reduce((sum, product) => sum + ((product.option_values || {})[attribute.attribute_id]?.length || 0), 0); const scopeLabel = DEFAULT_VARIANT_FIELDS.has(attribute.attribute_id) ? "default" : "custom"; return { ...attribute, productsUsing: productsUsing.length, valueCount, scopeLabel }; }).filter((attribute) => (scope !== "all" ? attribute.scopeLabel === scope : true) && (!search || `${attribute.name} ${attribute.attribute_id}`.toLowerCase().includes(search.toLowerCase()))), [attributes, products, scope, search]);
  if ((loading || loadingProducts) && !attributes.length && !products.length) return <LoadingPanel title="Loading attributes" message="Inspecting dynamic attribute usage across your grouped catalogue." variant="cards" />;
  return <div className="grid gap-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="m-0 text-3xl font-bold text-slate-900">Attributes</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-slate-500">Track which attributes power your variant system and which dynamic fields came in from supplier files.</p></div><Link to="/admin/import" className="btn-outline">Open importer</Link></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><div className="stat-card"><strong className="text-3xl font-bold text-slate-900">{attributes.length}</strong><div className="mt-2 text-sm text-slate-500">Registered attributes</div></div><div className="stat-card"><strong className="text-3xl font-bold text-slate-900">{attributes.filter((attribute) => DEFAULT_VARIANT_FIELDS.has(attribute.attribute_id)).length}</strong><div className="mt-2 text-sm text-slate-500">Default variant fields</div></div><div className="stat-card"><strong className="text-3xl font-bold text-slate-900">{attributes.filter((attribute) => !DEFAULT_VARIANT_FIELDS.has(attribute.attribute_id)).length}</strong><div className="mt-2 text-sm text-slate-500">Custom attributes</div></div></div><div className="surface-card grid gap-4 p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="m-0 text-xl font-semibold text-slate-900">Attribute registry</h2><p className="mt-2 text-sm text-slate-500">Filter by built-in or custom attributes and see how widely each field is used.</p></div><div className="flex flex-wrap gap-3"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search attributes" className="field-input max-w-xs" /><select value={scope} onChange={(event) => setScope(event.target.value)} className="field-input max-w-xs"><option value="all">All scopes</option><option value="default">Default variant fields</option><option value="custom">Custom attributes</option></select></div></div>{!summaries.length ? <div className="text-sm text-slate-500">No attributes matched your filters.</div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{summaries.map((attribute) => <article key={attribute.attribute_id || attribute.name} className="rounded-3xl border border-slate-200 bg-slate-50/70 p-5"><div className="grid gap-3"><div className="flex items-start justify-between gap-3"><h3 className="m-0 text-lg font-semibold text-slate-900">{attribute.name}</h3><span className={attribute.scopeLabel === "default" ? "chip-blue" : "chip-violet"}>{attribute.scopeLabel}</span></div><div className="text-sm text-slate-500">Key: {attribute.attribute_id}</div><div className="grid gap-2 text-sm text-slate-600"><div><strong>Type:</strong> {attribute.type || "text"}</div><div><strong>Products using it:</strong> {attribute.productsUsing}</div><div><strong>Distinct value slots:</strong> {attribute.valueCount}</div></div></div></article>)}</div>}</div></div>;
};

export default AdminAttributesPage;